# sequence and annotation files for each organism.
genomes:
  zea_mays:
    seq: ./genomes/zea_mays/GCF_902167145.1_Zm-B73-REFERENCE-NAM-5.0_genomic.fna
    ann: ./genomes/zea_mays/zma.gff3
  oryza_sativa_japonica:
    seq: ./genomes/oryza_sativa_japonica/GCF_001433935.1_IRGSP-1.0_genomic.fna
    ann: ./genomes/oryza_sativa_japonica/osa.gff3

# number of sequences you would like to process
nseqs: 10
